[package]
name = "doctor-diff-core"
version = "0.1.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"

[dependencies]
ring = "0.16"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
zip = "0.5"
