[package]
name = "doctor-diff-cli"
version = "0.1.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"

[[bin]]
name = "doctor-diff"
path = "./src/main.rs"

[dependencies]
doctor-diff-core = { version = "0.1", path = "../doctor-diff-core" }
clap = "2.33"
